### PR TITLE
mangled minification doesn't work because of ngAnnotate failing to recog...

### PR DESCRIPTION
**Pull request by lookfirst**
...nize this injection

tried to figure out how to get ngAnnotate to force the annotation, but it just wouldn't catch on. tried everything but wrapping in a ngAnnotate method, which seemed a bit hacky.

### CODE REVIEW

**Comment by amcdnl** [comment]
Mangle is such a pain with angular.  good find.

**Comment by lookfirst** [comment]
The trick was to turn on the mangle checking in angular (but not in uglify) and then grep the code for the method that showed up in the console.

**Comment by amcdnl** [comment]
Oh, can you show an example?

**Comment by lookfirst** [comment]
1. https://github.com/lookfirst/systemjs-seed/blob/50ddf837dbf46202a5bc3f063329011ea6c1adaf/src/app/app.coffee#L18
2. Revert this patch

Load up the app and look in the console. Angular will show an error and the function that isn't being injected properly. From there, I just grepped for the arguments in that function and route.js came right up.

Note, the first link above is my fork of your project. I want things like CS support and a CS gulpfile, even if you don't. =)

**Pull request merged**
